-- 주문량이 많은 아이스크림들 조회하기
SELECT f.FLAVOR
FROM FIRST_HALF f 
JOIN 
(
    SELECT FLAVOR, SUM(TOTAL_ORDER) as TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
) as j 
ON f.FLAVOR = j.FLAVOR
ORDER BY (f.TOTAL_ORDER + j.TOTAL_ORDER) DESC 
LIMIT 3;


-- 저자 별 카테고리 별 매출액 집계하기
SELECT b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(bs.SALES * b.PRICE) as TOTAL_SALES
FROM BOOK as b
JOIN AUTHOR as a
ON b.AUTHOR_ID = a.AUTHOR_ID
JOIN BOOK_SALES as bs
ON b.BOOK_ID = bs.BOOK_ID
WHERE date_format(bs.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY 2,3
ORDER BY 1, 3 DESC;
