— 강원도에 위치한 생산공장 목록 출력하기
SELECT FACTORY_ID, FACTORY_NAME, ADDRESS FROM FOOD_FACTORY 
WHERE ADDRESS LIKE "강원도%" ORDER BY FACTORY_ID ASC;

— 경기도에 위치한 식품창고 목록 출력하기
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, IFNULL(FREEZER_YN, "N") AS FREEZER_YN FROM FOOD_WAREHOUSE 
WHERE ADDRESS LIKE "경기도%" ORDER BY WAREHOUSE_ID ASC;

— 나이 정보가 없는 회원 수 구하기
SELECT COUNT(USER_ID) AS USERS FROM USER_INFO WHERE AGE IS NULL;

— 조건에 맞는 회원수 구하기
SELECT COUNT(USER_ID) AS USERS FROM USER_INFO 
WHERE AGE BETWEEN 20 AND 29 AND YEAR(JOINED) = 2021;

— 가장 비싼 상품 구하기
SELECT PRICE AS MAX_PRICE FROM PRODUCT ORDER BY PRICE DESC LIMIT 1;
