-- 12세 이하인 여자 환자 목록 출력하기
SELECT PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO, "NONE") AS TLNO FROM PATIENT 
WHERE GEND_CD = 'W' AND AGE <= 12 
ORDER BY AGE DESC, PT_NAME ASC;

-- 흉부외과 또는 일반외과 의사 목록 출력하기
SELECT DR_NAME, DR_ID, MCDP_CD, DATE_FORMAT(HIRE_YMD, "%Y-%m-%d") AS HIRE_YMD FROM DOCTOR 
WHERE MCDP_CD = "CS" OR MCDP_CD = "GS" ORDER BY HIRE_YMD DESC, DR_NAME ASC;

-- 인기있는 아이스크림
SELECT FLAVOR FROM FIRST_HALF ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID ASC;

-- 과일로 만든 아이스크림 고르기
SELECT F.FLAVOR FROM FIRST_HALF F 
JOIN ICECREAM_INFO I 
USING(FLAVOR)
WHERE TOTAL_ORDER > 3000 AND INGREDIENT_TYPE = "fruit_based"
ORDER BY TOTAL_ORDER DESC;
