-- 오랜 기간 보호한 동물(2)
SELECT I.animal_id, I.name
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC
LIMIT 2;


-- 헤비 유저가 소유한 장소
/*
SELECT ID, NAME, HOST_ID
FROM PLACES
WHERE HOST_ID IN (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(*) > 1
)
ORDER BY ID
*/


SELECT P.ID, P.NAME, P.HOST_ID
FROM PLACES P
JOIN (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(*) > 1
) T ON P.HOST_ID = T.HOST_ID 


-- 조건별로 분류하여 주문상태 출력하기
SELECT 
    ORDER_ID
    , PRODUCT_ID
    , DATE_FORMAT(OUT_DATE,'%Y-%m-%d') AS OUT_DATE
    , CASE
        WHEN OUT_DATE > DATE('2022-05-01') THEN '출고대기'
        WHEN OUT_DATE <= DATE('2022-05-01') THEN '출고완료'
        WHEN OUT_DATE IS NULL THEN '출고미정'
     END AS '출고여부'
FROM FOOD_ORDER
ORDER BY ORDER_ID;
