-- 12세 이하인 여자 환자 목록 출력하기
SELECT 
    PT_NAME,
    PT_NO,
    GEND_CD,
    AGE,
    IFNULL(TLNO, 'NONE')
FROM
    PATIENT
WHERE
    AGE <= 12
    AND GEND_CD = 'W'
ORDER BY AGE DESC, PT_NAME;


-- 흉부외과 또는 일반외과 의사 목록 출력하기
SELECT
    DR_NAME,
    DR_ID,
    MCDP_CD,
    DATE_FORMAT(HIRE_YMD, '%Y-%m-%d')
    HIRE_YMD
FROM 
    DOCTOR
WHERE
    MCDP_CD = 'CS' OR MCDP_CD = 'GS'
ORDER BY HIRE_YMD DESC, DR_NAME;


-- 인기있는 아이스크림
SELECT FLAVOR
FROM FIRST_HALF
ORDER BY TOTAL_ORDER DESC, SHIPMENT_ID;


-- 과일로 만든 아이스크림 고르기
SELECT A.FLAVOR
FROM FIRST_HALF A
JOIN ICECREAM_INFO B ON A.FLAVOR = B.FLAVOR
WHERE A.TOTAL_ORDER > 3000
AND B.INGREDIENT_TYPE = 'fruit_based'
ORDER BY A.TOTAL_ORDER DESC;
