보호소에서 중성화한 동물
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE != O.SEX_UPON_OUTCOME
ORDER BY O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME

입양 시각 구하기(2)
SET @HOUR_COUNT:=-1;
SELECT @HOUR_COUNT:=@HOUR_COUNT+1 as HOUR, 
IFNULL((SELECT COUNT(DATETIME) 
       FROM ANIMAL_OUTS 
       WHERE @HOUR_COUNT = HOUR(DATETIME) 
       GROUP BY HOUR(DATETIME)), 0) AS COUNT 
FROM ANIMAL_OUTS
WHERE @HOUR_COUNT < 23
