59403
SELECT ANIMAL_ID, NAME from ANIMAL_INS order by ANIMAL_ID ASC

59404
SELECT ANIMAL_ID, NAME, DATETIME from ANIMAL_INS group by 2, 3 order by name asc, datetime desc

59405
SELECT NAME from ANIMAL_INS order by datetime asc limit 1

59407
SELECT ANIMAL_ID FROM ANIMAL_INS WHERE NAME IS NOT NULL ORDER BY ANIMAL_ID ASC

59415
SELECT MAX(DATETIME) AS 시간 FROM ANIMAL_INS

59039
SELECT ANIMAL_ID FROM ANIMAL_INS WHERE NAME IS NULL ORDER BY ANIMAL_ID AS:
