이름에 el이 들어가는 동물 찾기
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS
WHERE ANIMAL_TYPE="Dog" AND NAME LIKE "%EL%"
ORDER BY NAME ASC

동물 수 구하기
SELECT COUNT(*) FROM ANIMAL_INS

중복 제거하기
SELECT COUNT(DISTINCT NAME) AS COUNT FROM ANIMAL_INS

중성화 여부 파악하기
SELECT ANIMAL_ID, NAME, 
(CASE WHEN SEX_UPON_INTAKE LIKE '%NEUTERED%' OR SEX_UPON_INTAKE LIKE '%SPAYED%' THEN 'O' 
 ELSE 'X' END) AS 중성화 FROM ANIMAL_INS
