3월에 태어난 여성 회원 목록 출력하기
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH, "%Y-%m-%d") AS DATE_FOR_BIRTH FROM MEMBER_PROFILE
WHERE GENDER = 'W' AND TLNO IS NOT NULL AND DATE_FORMAT(DATE_OF_BIRTH, "%m") = "03"

카테고리 별 상품 개수 구하기
SELECT LEFT(PRODUCT_CODE, 2)AS CATEGORY, COUNT(LEFT(PRODUCT_CODE, 2)) AS PRODUCTS FROM PRODUCT
GROUP BY CATEGORY
ORDER BY CATEGORY ASC

가격대 별 상품 개수 구하기
SELECT FLOOR(PRICE/10000)*10000 AS PRICE_GROUP, COUNT(PRODUCT_ID) AS PRODUCT FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP ASC

상품 별 오프라인 매출 구하기
SELECT PRODUCT_CODE, SUM(a.PRICE*b.SALES_AMOUNT) AS SALES FROM PRODUCT a
JOIN OFFLINE_SALE b ON a.PRODUCT_ID = b.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC
