-- 자동차 대여 기록 별 대여 금액 구하기
WITH PLAN AS 
    (
        SELECT car_type, DISCOUNT_RATE, DURATION_TYPE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE = '트럭'
    )

SELECT HISTORY_ID, ROUND(DURATION*DAILY_FEE*(100-COALESCE(DISCOUNT_RATE,0))/100) FEE
FROM (
    SELECT HISTORY_ID, DATEDIFF(END_DATE, START_DATE)+1 AS DURATION, DAILY_FEE, 
        CASE WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN (SELECT DISCOUNT_RATE FROM PLAN WHERE DURATION_TYPE = '90일 이상')
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN (SELECT DISCOUNT_RATE FROM PLAN WHERE DURATION_TYPE = '30일 이상')
        WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 THEN (SELECT DISCOUNT_RATE FROM PLAN WHERE DURATION_TYPE = '7일 이상')
        END AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
) SUB
ORDER BY FEE DESC, HISTORY_ID DESC

WITH INFO AS
    (
        SELECT HISTORY_ID, CAR_TYPE, DATEDIFF(END_DATE, START_DATE)+1 AS DAYS, DAILY_FEE, 
            CASE WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 90 THEN '90일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 30 THEN '30일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE)+1 >= 7 THEN '7일 이상'
            END AS DURATION_TYPE
        FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
        WHERE C.CAR_TYPE = '트럭'
    )

SELECT I.HISTORY_ID, ROUND(DAYS * DAILY_FEE*(100-COALESCE(P.DISCOUNT_RATE,0))/100) AS FEE
FROM INFO I LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON I.CAR_TYPE=P.CAR_TYPE AND I.DURATION_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;


-- 특정 기간동안 대여 가능한 자동차들의 대여비용 구하기
SELECT C.CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE * 30 * (100-P.DISCOUNT_RATE)/100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV') AND P.DURATION_TYPE='30일 이상'
    AND C.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
HAVING FEE >= 500000 AND FEE < 2000000 
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC