-- 조회수가 가장 많은 중고거래 게시판의 첨부파일 조회하기
SELECT CONCAT( '/home/grep/src/' , BOARD_ID , '/' , FILE_ID , FILE_NAME , FILE_EXT ) AS FILE_PATH
FROM USED_GOODS_FILE 
WHERE BOARD_ID = (SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1)
ORDER BY FILE_ID DESC

-- 대여 기록이 존재하는 자동차 리스트 구하기
SELECT DISTINCT(C.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '세단' AND DATE_FORMAT(START_DATE, '%m') = '10'
ORDER BY C.CAR_ID DESC