-- 즐겨찾기가 가장 많은 식당 정보 출력하기
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES 
FROM (
    SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES
    FROM REST_INFO 
    GROUP BY FOOD_TYPE
) X INNER JOIN REST_INFO RI ON X.FOOD_TYPE = RI.FOOD_TYPE AND X.FAVORITES = RI.FAVORITES
ORDER BY FOOD_TYPE DESC;

-- 카테고리 별 도서 판매량 집계하기
SELECT CATEGORY, SUM(BS.SALES) TOTAL_SALES FROM BOOK B 
LEFT JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
WHERE DATE_FORMAT(BS.SALES_DATE, "%Y-%m") = "2022-01"
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;

-- 대여 횟수가 많은 자동차들의 월별 대여 횟수 구하기
SELECT MONTH(START_DATE) MONTH, C.CAR_ID, COUNT(*) RECORDS 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
INNER JOIN (
    SELECT CAR_ID, COUNT(*) CNT FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
    GROUP BY 1
) X ON X.CAR_ID = C.CAR_ID 
WHERE X.CNT >= 5 AND (START_DATE BETWEEN "2022-08-01" AND "2022-10-31")
GROUP BY 1, 2
HAVING COUNT(*) > 0
ORDER BY 1, 2 DESC;
