-- 보호소에서 중성화한 동물
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM
    (
    SELECT *
    FROM ANIMAL_INS
    WHERE SEX_UPON_INTAKE LIKE "%Intact%"
    ) S, ANIMAL_OUTS AS O
WHERE S.ANIMAL_ID = O.ANIMAL_ID
AND O.SEX_UPON_OUTCOME NOT LIKE "%Intact%";

-- 입양 시각 구하기(2)
WITH RECURSIVE HOUR AS (
	SELECT 0 AS h
	UNION ALL
	SELECT h+1 FROM hour WHERE h<23
)

SELECT hour.h AS hour, COUNT(hour(a.DATETIME)) AS count FROM hour
LEFT JOIN ANIMAL_OUTS AS a ON hour.h = hour(a.DATETIME)
GROUP BY 1
ORDER BY 1;
