-- 우유와 요거트가 담긴 장바구니
SELECT CR1.CART_ID FROM CART_PRODUCTS CR1 JOIN CART_PRODUCTS CR2 ON CR1.CART_ID = CR2.CART_ID 
WHERE CR1.NAME='Milk' AND CR2.NAME='Yogurt' ORDER BY CR1.ID;;

-- 식품분류별 가장 비싼 식품의 정보 조회하기
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE (CATEGORY, PRICE) IN (
    SELECT CATEGORY, MAX(PRICE)
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)
ORDER BY MAX_PRICE DESC;
