-- 재구매가 일어난 상품과 회원 리스트 구하기
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID
HAVING COUNT(*) > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC;

-- 진료과별 총 예약 횟수 출력하기
SELECT MCDP_CD 진료과코드, COUNT(*) 5월예약건수
FROM APPOINTMENT
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m') = '2022-05'
GROUP BY MCDP_CD
ORDER BY 5월예약건수, 진료과코드;

-- 성분으로 구분한 아이스크림 총 주문량
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER 
FROM ICECREAM_INFO ii 
JOIN FIRST_HALF fh ON ii.FLAVOR = fh.FLAVOR 
GROUP BY INGREDIENT_TYPE 
ORDER BY TOTAL_ORDER ASC;

-- 조건에 맞는 도서와 저자 리스트 출력하기
SELECT b.BOOK_ID, a.AUTHOR_NAME, DATE_FORMAT(b.PUBLISHED_DATE, "%Y-%m-%d") PUBLISHED_DATE 
FROM BOOK b 
JOIN AUTHOR a ON b.AUTHOR_ID = a.AUTHOR_ID 
WHERE b.CATEGORY='경제' 
ORDER BY PUBLISHED_DATE ASC;
